### ISSUE TITLE
READ THE NEEDFUL

### ISSUE THREAD

**Issue by kirtipndt12** [krupalhp2907/dashboard#13] opened 2020-07-23 06:35 UTC
BUG LIFE CYCLE:
![Bug-Lifecycle](https://user-images.githubusercontent.com/46815975/88258026-c2207580-ccdc-11ea-950d-c63307efcca4.jpg)
@krupalhp2907

**Comment by krupalhp2907** [comment] 2020-08-07 11:35
Duplicate of #12

**Comment by krupalhp2907** [comment] 2020-08-07 11:35
Testing github #1

**Comment by krupalhp2907** [comment] 2020-08-07 11:44
Close #14

**Comment by krupalhp2907** [comment] 2020-08-07 11:44
#12 duplicate

**Comment by krupalhp2907** [comment] 2020-08-07 11:46
dependencies of #12

**Comment by krupalhp2907** [comment] 2020-08-07 11:46
duplicate of #12
this is some random text.
another random text

**Comment by krupalhp2907** [comment] 2020-08-07 11:49
#12

**Comment by krupalhp2907** [comment] 2020-08-07 11:49
duplicate of #12
see details

**Closed as completed** 2020-09-06 21:27 UTC
Labels: bug, documentation, dependencies
